### ISSUE TITLE
support inputs other than .wav

### ISSUE THREAD

**Issue by Baenwort** [Topping1/whispercppGUI#1]
Do you think you might automate the conversion to .wav and input into whisper.cpp? Since ffmpeg can also be installed you could take the step off the user to do the conversion separately and then feed your GUI the .wav to reduce errors.

**Comment by Topping1** [comment]
@Baenwort took some time but now whispercppGUI uses ffmpeg to automatically convert the input file to the WAV file whispercpp requires. Thanks for your feedback.
