### ISSUE TITLE
FR: Update to support BLAS/Llama/q4 models?

### ISSUE THREAD

**Issue by brimwats** [Topping1/whispercppGUI#5]
Thank you for your work on this! It's been the best GUI by miles.

This only works with the early stuff and doesn't allow me to use the q4 ggml models for example. It would be nice to try out the BLAS stuff through it too.

**Comment by Topping1** [comment]
you only have to download the latest version from [here](https://github.com/ggerganov/whisper.cpp/releases) and overwrite the old files and you can use quantized models.
